=== powsybl/powsybl-open-rao/data/crac/crac-io/crac-io-json/src/main/resources/schemas/crac/crac-v2.1.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema#",
  "$id": "resource:/schemas/crac/crac-v2.1.json",
  "description": "Contingency list, Remedial Actions and additional Constraints",
  "title": "CRAC",
  "type": "object",
  "properties": {
    "type": {
      "const": "CRAC"
    },
    "version": {
      "const": "2.1"
    },
    "info": {
      "description": "Information about the CRAC",
      "type": "string"
    },
    "id": {
      "description": "The unique identifier of the CRAC",
      "type": "string"
    },
    "name": {
      "description": "The name of the CRAC",
      "type": "string"
    },
    "instants": {
      "description": "The list of instants at which a CNEC can be monitored and a Remedial Action applied",
      "type": "array",
      "items": {
        "$ref": "../instant/instant-v2.0.json"
      }
    },
    "ra-usage-limits-per-instant": {
      "description": "The list of remedial action usage limitations for each instant",
      "type": "array",
      "items": {
        "$ref": "../ra-usage-limits-per-instant/ra-usage-limits-per-instant-v2.1.json"
      }
    },
    "networkElementsNamePerId": {
      "description": "A map of network element names indexed by their identifiers",
      "type": "object",
      "additionalProperties": {
        "type": "string"
      }
    },
    "contingencies": {
      "description": "The list of contingencies to be studied",
      "type": "array",
      "items": {
        "$ref": "../contingency/contingency-v1.0.json"
      }
    },
    "flowCnecs": {
      "description": "The list of flow CNECs to be monitored",
      "type": "array",
      "items": {
        "items": {
          "$ref": "../flow-cnec/flow-cnec-v1.7.json"
        }
      }
    },
    "angleCnecs": {
      "description": "The list of angle CNECs to be monitored",
      "type": "array",
      "items": {
        "items": {
          "$ref": "../angle-cnec/angle-cnec-v1.4.json"
        }
      }
    },
    "voltageCnecs": {
      "description": "The list of voltage CNECs to be monitored",
      "type": "array",
      "items": {
        "items": {
          "$ref": "../voltage-cnec/voltage-cnec-v1.5.json"
        }
      }
    },
    "pstRangeActions": {
      "description": "The list of PST range actions",
      "type": "array",
      "items": {
        "$ref": "../pst-range-action/pst-range-action-v2.0.json"
      }
    },
    "hvdcRangeActions": {
      "description": "The list of HVDC range actions",
      "type": "array",
      "items": {
        "$ref": "../hvdc-range-action/hvdc-range-action-v2.0.json"
      }
    },
    "injectionRangeActions": {
      "description": "The list of injection range actions",
      "type": "array",
      "items": {
        "$ref": "../injection-range-action/injection-range-action-v2.0.json"
      }
    },
    "counterTradeRangeActions": {
      "description": "The list of counter-trade range actions",
      "type": "array",
      "items": {
        "$ref": "../counter-trade-range-action/counter-trade-range-action-v2.0.json"
      }
    },
    "networkActions": {
      "description": "The list of network actions",
      "type": "array",
      "items": {
        "$ref": "../network-action/network-action-v2.0.json"
      }
    }
  },
  "additionalProperties": false,
  "required": [
    "type",
    "version",
    "id",
    "name"
  ]
}

=== powsybl/powsybl-open-rao/tests/src/test/resources/files/crac/epic91/crac_91_12_24_with_ra_limitations.json
{
  "type": "CRAC",
  "version": "2.1",
  "info": "Generated by FARAO http://farao-community.github.io",
  "id": "CRAC_91_12_2",
  "name": "CRAC_91_12_2",
  "instants": [
    {
      "id" : "preventive",
      "kind" : "PREVENTIVE"
    },
    {
      "id" : "outage",
      "kind" : "OUTAGE"
    },
    {
      "id" : "curative1",
      "kind" : "CURATIVE"
    },
    {
      "id" : "curative2",
      "kind" : "CURATIVE"
    },
    {
      "id" : "curative3",
      "kind" : "CURATIVE"
    }
  ],
  "ra-usage-limits-per-instant" :  [ {
    "instant": "curative1",
    "max-ra": 0
  }, {
    "instant": "curative2",
    "max-ra": 1
  }, {
    "instant": "curative3",
    "max-ra": 1
  } ],
  "networkElementsNamePerId": {},
  "contingencies": [
    {
      "id": "Contingency DE2 DE3 1",
      "networkElementsIds": [
        "DDE2AA1  DDE3AA1  1"
      ]
    }
  ],
  "flowCnecs": [
    {
      "id": "NNL2AA1  BBE3AA1  1 - preventive",
      "name": "NNL2AA1  BBE3AA1  1 - preventive",
      "networkElementId": "NNL2AA1  BBE3AA1  1",
      "operator": null,
      "instant": "preventive",
      "optimized": true,
      "monitored": false,
      "reliabilityMargin": 0.0,
      "iMax": [
        5000.0
      ],
      "nominalV": [
        400.0
      ],
      "thresholds": [
        {
          "unit": "megawatt",
          "min": -800.0,
          "max": 800.0,
          "side" : "left"
        }
      ]
    },
    {
      "id": "NNL2AA1  BBE3AA1  1 - Contingency DE2 DE3 1 - outage",
      "name": "NNL2AA1  BBE3AA1  1 - Contingency DE2 DE3 1 - outage",
      "networkElementId": "NNL2AA1  BBE3AA1  1",
      "contingencyId": "Contingency DE2 DE3 1",
      "operator": null,
      "instant": "outage",
      "optimized": true,
      "monitored": false,
      "reliabilityMargin": 0.0,
      "iMax": [
        50.0
      ],
      "nominalV": [
        400.0
      ],
      "thresholds": [
        {
          "unit": "megawatt",
          "min": -1000.0,
          "max": 1000.0,
          "side" : "left"
        }
      ]
    },
    {
      "id": "NNL2AA1  BBE3AA1  1 - Contingency DE2 DE3 1 - curative1",
      "name": "NNL2AA1  BBE3AA1  1 - Contingency DE2 DE3 1 - curative1",
      "networkElementId": "NNL2AA1  BBE3AA1  1",
      "contingencyId": "Contingency DE2 DE3 1",
      "operator": null,
      "instant": "curative1",
      "optimized": true,
      "monitored": false,
      "reliabilityMargin": 0.0,
      "iMax": [
        50.0
      ],
      "nominalV": [
        400.0
      ],
      "thresholds": [
        {
          "unit": "megawatt",
          "min": -500.0,
          "max": 500.0,
          "side" : "left"
        }
      ]
    },
    {
      "id": "NNL2AA1  BBE3AA1  1 - Contingency DE2 DE3 1 - curative2",
      "name": "NNL2AA1  BBE3AA1  1 - Contingency DE2 DE3 1 - curative2",
      "networkElementId": "NNL2AA1  BBE3AA1  1",
      "contingencyId": "Contingency DE2 DE3 1",
      "operator": null,
      "instant": "curative2",
      "optimized": true,
      "monitored": false,
      "reliabilityMargin": 0.0,
      "iMax": [
        50.0
      ],
      "nominalV": [
        400.0
      ],
      "thresholds": [
        {
          "unit": "megawatt",
          "min": -300.0,
          "max": 300.0,
          "side" : "left"
        }
      ]
    },
    {
      "id": "NNL2AA1  BBE3AA1  1 - Contingency DE2 DE3 1 - curative3",
      "name": "NNL2AA1  BBE3AA1  1 - Contingency DE2 DE3 1 - curative3",
      "networkElementId": "NNL2AA1  BBE3AA1  1",
      "contingencyId": "Contingency DE2 DE3 1",
      "operator": null,
      "instant": "curative3",
      "optimized": true,
      "monitored": false,
      "reliabilityMargin": 0.0,
      "iMax": [
        50.0
      ],
      "nominalV": [
        400.0
      ],
      "thresholds": [
        {
          "unit": "megawatt",
          "min": -250.0,
          "max": 250.0,
          "side" : "left"
        }
      ]
    }
  ],
  "pstRangeActions": [
    {
      "id": "CRA_PST_BE",
      "name": "CRA_PST_BE",
      "operator": "BE",
      "onInstantUsageRules": [
        {
          "instant": "curative2",
          "usageMethod": "available"
        },
        {
          "instant": "curative3",
          "usageMethod": "available"
        }
      ],
      "networkElementId": "BBE2AA1  BBE3AA1  1",
      "initialTap": 0,
      "tapToAngleConversionMap": {
        "-1": -0.3896097993971608,
        "0": 0.0,
        "-2": -0.7792105912934298,
        "1": 0.3896097993971608,
        "-3": -1.1687933694373345,
        "2": 0.7792105912934298,
        "-4": -1.5583491300758083,
        "3": 1.1687933694373345,
        "-5": -1.9478688732023104,
        "4": 1.5583491300758083,
        "-6": -2.337343603803646,
        "5": 1.9478688732023104,
        "-7": -2.7267643331050597,
        "6": 2.337343603803646,
        "-8": -3.1161220798131644,
        "7": 2.7267643331050597,
        "-9": -3.505407871356285,
        "8": 3.1161220798131644,
        "-10": -3.894612745121778,
        "9": 3.505407871356285,
        "-11": -4.283727749689918,
        "10": 3.894612745121778,
        "-12": -4.672743946063913,
        "11": 4.283727749689918,
        "-13": -5.061652408895631,
        "12": 4.672743946063913,
        "-14": -5.4504442277066305,
        "13": 5.061652408895631,
        "-15": -5.839110508104064,
        "14": 5.4504442277066305,
        "-16": -6.2276423729910535,
        "15": 5.839110508104064,
        "16": 6.2276423729910535
      },
      "ranges": [
        {
          "min": -16,
          "max": 16,
          "rangeType": "absolute"
        }
      ]
    }
  ],
  "hvdcRangeActions": [],
  "injectionRangeActions": [],
  "networkActions": [
    {
      "id": "PRA_CLOSE_NL2_BE3_3",
      "name": "PRA_CLOSE_NL2_BE3_3",
      "operator": "BE",
      "onInstantUsageRules": [
        {
          "instant": "preventive",
          "usageMethod": "available"
        }
      ],
      "topologicalActions": [
        {
          "networkElementId": "NNL2AA1  BBE3AA1  3",
          "actionType": "close"
        }
      ]
    },
    {
      "id": "Useless_CRA",
      "name": "Useless_CRA",
      "operator": "BE",
      "onInstantUsageRules": [
        {
          "instant": "curative1",
          "usageMethod": "available"
        },
        {
          "instant": "curative2",
          "usageMethod": "available"
        },
        {
          "instant": "curative3",
          "usageMethod": "available"
        }
      ],
      "topologicalActions": [
        {
          "networkElementId": "NNL2AA1  BBE3AA1  3",
          "actionType": "open"
        }
      ]
    }
  ]
}

=== powsybl/powsybl-open-rao/tests/src/test/resources/files/crac/epic19/SL_ep19us2case4.json
{
  "type" : "CRAC",
  "version" : "2.1",
  "info" : "Generated by Open RAO http://farao-community.github.io",
  "id" : "curative_9",
  "name" : "curative_9",
  "instants" : [ {
    "id" : "preventive",
    "kind" : "PREVENTIVE"
  }, {
    "id" : "outage",
    "kind" : "OUTAGE"
  }, {
    "id" : "auto",
    "kind" : "AUTO"
  }, {
    "id" : "curative",
    "kind" : "CURATIVE"
  } ],
  "ra-usage-limits-per-instant" : [ {
    "instant": "curative",
    "max-ra" : 2147483647,
    "max-tso" : 2147483647,
    "max-topo-per-tso" : {
      "be" : 0
    },
    "max-pst-per-tso" : { },
    "max-ra-per-tso" : { }
  }, {
    "instant": "preventive",
    "max-ra" : 0
  } ],
  "networkElementsNamePerId" : { },
  "contingencies" : [ {
    "id" : "co1_fr2_fr3_1",
    "networkElementsIds" : [ "FFR2AA1  FFR3AA1  1" ]
  }, {
    "id" : "co2_be1_be3",
    "networkElementsIds" : [ "BBE1AA1  BBE3AA1  1", "BBE1AA1  BBE3AA1  2" ]
  } ],
  "flowCnecs" : [ {
    "id" : "BBE2AA1  FFR3AA1  1 - co2_be1_be3 - curative",
    "name" : "be2_fr3",
    "networkElementId" : "BBE2AA1  FFR3AA1  1",
    "operator" : null,
    "instant" : "curative",
    "contingencyId" : "co2_be1_be3",
    "optimized" : true,
    "monitored" : false,
    "reliabilityMargin" : 0.0,
    "iMax" : [ 2000.0 ],
    "nominalV" : [ 400.0 ],
    "thresholds" : [ {
      "unit" : "ampere",
      "min" : -1500.0,
      "max" : 1500.0,
      "side" : "right"
    } ]
  }, {
    "id" : "FFR3AA1  FFR5AA1  1 - co1_fr2_fr3_1 - curative",
    "name" : "fr3_fr5",
    "networkElementId" : "FFR3AA1  FFR5AA1  1",
    "operator" : null,
    "instant" : "curative",
    "contingencyId" : "co1_fr2_fr3_1",
    "optimized" : true,
    "monitored" : false,
    "reliabilityMargin" : 0.0,
    "iMax" : [ 2000.0 ],
    "nominalV" : [ 400.0 ],
    "thresholds" : [ {
      "unit" : "ampere",
      "min" : -1000.0,
      "max" : 1000.0,
      "side" : "right"
    } ]
  }, {
    "id" : "FFR4AA1  DDE1AA1  1 - co1_fr2_fr3_1 - curative",
    "name" : "fr4_de1",
    "networkElementId" : "FFR4AA1  DDE1AA1  1",
    "operator" : null,
    "instant" : "curative",
    "contingencyId" : "co1_fr2_fr3_1",
    "optimized" : true,
    "monitored" : false,
    "reliabilityMargin" : 0.0,
    "iMax" : [ 2000.0 ],
    "nominalV" : [ 400.0 ],
    "thresholds" : [ {
      "unit" : "ampere",
      "min" : -1500.0,
      "max" : 1500.0,
      "side" : "right"
    } ]
  }, {
    "id" : "FFR4AA1  DDE1AA1  1 - co2_be1_be3 - curative",
    "name" : "fr4_de1",
    "networkElementId" : "FFR4AA1  DDE1AA1  1",
    "operator" : null,
    "instant" : "curative",
    "contingencyId" : "co2_be1_be3",
    "optimized" : true,
    "monitored" : false,
    "reliabilityMargin" : 0.0,
    "iMax" : [ 2000.0 ],
    "nominalV" : [ 400.0 ],
    "thresholds" : [ {
      "unit" : "ampere",
      "min" : -1500.0,
      "max" : 1500.0,
      "side" : "right"
    } ]
  }, {
    "id" : "FFR4AA1  DDE1AA1  1 - preventive",
    "name" : "fr4_de1",
    "networkElementId" : "FFR4AA1  DDE1AA1  1",
    "operator" : null,
    "instant" : "preventive",
    "optimized" : true,
    "monitored" : false,
    "reliabilityMargin" : 0.0,
    "iMax" : [ 2000.0 ],
    "nominalV" : [ 400.0 ],
    "thresholds" : [ {
      "unit" : "ampere",
      "min" : -1500.0,
      "max" : 1500.0,
      "side" : "right"
    } ]
  }, {
    "id" : "NNL2AA1  BBE3AA1  1 - preventive",
    "name" : "nl2_be3",
    "networkElementId" : "NNL2AA1  BBE3AA1  1",
    "operator" : null,
    "instant" : "preventive",
    "optimized" : true,
    "monitored" : false,
    "reliabilityMargin" : 0.0,
    "iMax" : [ 2000.0 ],
    "nominalV" : [ 400.0 ],
    "thresholds" : [ {
      "unit" : "ampere",
      "min" : -5000.0,
      "max" : 5000.0,
      "side" : "right"
    } ]
  } ],
  "angleCnecs" : [ ],
  "voltageCnecs" : [ ],
  "pstRangeActions" : [ {
    "id" : "pst_be",
    "name" : "pst_be",
    "operator" : "be",
    "onInstantUsageRules" : [ {
      "instant" : "curative",
      "usageMethod" : "available"
    } ],
    "networkElementId" : "BBE2AA1  BBE3AA1  1",
    "initialTap" : 0,
    "tapToAngleConversionMap" : {
      "-1" : -0.3896097993971608,
      "0" : 0.0,
      "-2" : -0.7792105912934298,
      "1" : 0.3896097993971608,
      "-3" : -1.1687933694373345,
      "2" : 0.7792105912934298,
      "-4" : -1.5583491300758083,
      "3" : 1.1687933694373345,
      "-5" : -1.9478688732023104,
      "4" : 1.5583491300758083,
      "-6" : -2.337343603803646,
      "5" : 1.9478688732023104,
      "-7" : -2.7267643331050597,
      "6" : 2.337343603803646,
      "-8" : -3.1161220798131644,
      "7" : 2.7267643331050597,
      "-9" : -3.505407871356285,
      "8" : 3.1161220798131644,
      "-10" : -3.894612745121778,
      "9" : 3.505407871356285,
      "-11" : -4.283727749689918,
      "10" : 3.894612745121778,
      "-12" : -4.672743946063913,
      "11" : 4.283727749689918,
      "-13" : -5.061652408895631,
      "12" : 4.672743946063913,
      "-14" : -5.4504442277066305,
      "13" : 5.061652408895631,
      "-15" : -5.839110508104064,
      "14" : 5.4504442277066305,
      "-16" : -6.2276423729910535,
      "15" : 5.839110508104064,
      "16" : 6.2276423729910535
    },
    "ranges" : [ {
      "min" : -16,
      "max" : 16,
      "rangeType" : "absolute"
    } ]
  }, {
    "id" : "pst_fr",
    "name" : "pst_fr",
    "operator" : "fr",
    "onInstantUsageRules" : [ {
      "instant" : "preventive",
      "usageMethod" : "available"
    } ],
    "networkElementId" : "FFR2AA1  FFR4AA1  1",
    "initialTap" : 5,
    "tapToAngleConversionMap" : {
      "-1" : -0.3896097993971608,
      "0" : 0.0,
      "-2" : -0.7792105912934298,
      "1" : 0.3896097993971608,
      "-3" : -1.1687933694373345,
      "2" : 0.7792105912934298,
      "-4" : -1.5583491300758083,
      "3" : 1.1687933694373345,
      "-5" : -1.9478688732023104,
      "4" : 1.5583491300758083,
      "-6" : -2.337343603803646,
      "5" : 1.9478688732023104,
      "-7" : -2.7267643331050597,
      "6" : 2.337343603803646,
      "-8" : -3.1161220798131644,
      "7" : 2.7267643331050597,
      "-9" : -3.505407871356285,
      "8" : 3.1161220798131644,
      "-10" : -3.894612745121778,
      "9" : 3.505407871356285,
      "-11" : -4.283727749689918,
      "10" : 3.894612745121778,
      "-12" : -4.672743946063913,
      "11" : 4.283727749689918,
      "-13" : -5.061652408895631,
      "12" : 4.672743946063913,
      "-14" : -5.4504442277066305,
      "13" : 5.061652408895631,
      "-15" : -5.839110508104064,
      "14" : 5.4504442277066305,
      "-16" : -6.2276423729910535,
      "15" : 5.839110508104064,
      "16" : 6.2276423729910535
    },
    "ranges" : [ {
      "min" : -10,
      "max" : 10,
      "rangeType" : "relativeToInitialNetwork"
    } ]
  } ],
  "hvdcRangeActions" : [ ],
  "injectionRangeActions" : [ ],
  "counterTradeRangeActions" : [ ],
  "networkActions" : [ {
    "id" : "close_de3_de4",
    "name" : "close_de3_de4",
    "operator" : "de",
    "onInstantUsageRules" : [ {
      "instant" : "curative",
      "usageMethod" : "available"
    } ],
    "topologicalActions" : [ {
      "networkElementId" : "DDE3AA1  DDE4AA1  1",
      "actionType" : "close"
    } ]
  }, {
    "id" : "close_fr1_fr5",
    "name" : "close_fr1_fr5",
    "operator" : "fr",
    "onInstantUsageRules" : [ {
      "instant" : "preventive",
      "usageMethod" : "available"
    } ],
    "topologicalActions" : [ {
      "networkElementId" : "FFR1AA1  FFR5AA1  1",
      "actionType" : "close"
    } ]
  }, {
    "id" : "open_be1_be4",
    "name" : "open_be1_be4",
    "operator" : "be",
    "onInstantUsageRules" : [ {
      "instant" : "curative",
      "usageMethod" : "available"
    } ],
    "topologicalActions" : [ {
      "networkElementId" : "BBE1AA1  BBE4AA1  1",
      "actionType" : "open"
    } ]
  }, {
    "id" : "open_fr1_fr2",
    "name" : "open_fr1_fr2",
    "operator" : "fr",
    "onInstantUsageRules" : [ {
      "instant" : "curative",
      "usageMethod" : "available"
    } ],
    "topologicalActions" : [ {
      "networkElementId" : "FFR1AA1  FFR2AA1  1",
      "actionType" : "open"
    } ]
  }, {
    "id" : "open_fr1_fr3",
    "name" : "open_fr1_fr3",
    "operator" : "fr",
    "onInstantUsageRules" : [ {
      "instant" : "preventive",
      "usageMethod" : "available"
    } ],
    "topologicalActions" : [ {
      "networkElementId" : "FFR1AA1  FFR3AA1  1",
      "actionType" : "open"
    } ]
  } ]
}

=== powsybl/powsybl-open-rao/tests/src/test/resources/files/crac/epic19/SL_ep19us3case9.json
{
  "type" : "CRAC",
  "version" : "2.1",
  "info" : "Generated by Open RAO http://farao-community.github.io",
  "id" : "curative_3",
  "name" : "curative_3",
  "instants" : [ {
    "id" : "preventive",
    "kind" : "PREVENTIVE"
  }, {
    "id" : "outage",
    "kind" : "OUTAGE"
  }, {
    "id" : "auto",
    "kind" : "AUTO"
  }, {
    "id" : "curative",
    "kind" : "CURATIVE"
  } ],
  "ra-usage-limits-per-instant" : [ {
    "instant": "curative",
    "max-ra" : 2147483647,
    "max-tso" : 2147483647,
    "max-topo-per-tso" : {
      "be" : 0,
      "fr" : 0
    },
    "max-pst-per-tso" : {
      "be" : 0,
      "fr" : 0
    },
    "max-ra-per-tso" : {
      "be" : 0,
      "fr" : 0
    }
  } ],
  "networkElementsNamePerId" : { },
  "contingencies" : [ {
    "id" : "co1_fr2_fr3_1",
    "networkElementsIds" : [ "FFR2AA1  FFR3AA1  1" ]
  } ],
  "flowCnecs" : [ {
    "id" : "BBE1AA1  FFR5AA1  1 - preventive",
    "name" : "be1_fr5_n",
    "networkElementId" : "BBE1AA1  FFR5AA1  1",
    "operator" : null,
    "instant" : "preventive",
    "optimized" : true,
    "monitored" : false,
    "reliabilityMargin" : 0.0,
    "iMax" : [ 2000.0 ],
    "nominalV" : [ 400.0 ],
    "thresholds" : [ {
      "unit" : "ampere",
      "min" : -1500.0,
      "max" : 1500.0,
      "side" : "right"
    } ]
  }, {
    "id" : "BBE2AA1  FFR3AA1  1 - preventive",
    "name" : "be2_fr3_n",
    "networkElementId" : "BBE2AA1  FFR3AA1  1",
    "operator" : null,
    "instant" : "preventive",
    "optimized" : true,
    "monitored" : false,
    "reliabilityMargin" : 0.0,
    "iMax" : [ 2000.0 ],
    "nominalV" : [ 400.0 ],
    "thresholds" : [ {
      "unit" : "ampere",
      "min" : -1200.0,
      "max" : 1200.0,
      "side" : "right"
    } ]
  }, {
    "id" : "BBE4AA1  FFR5AA1  1 - preventive",
    "name" : "be4_fr5_n",
    "networkElementId" : "BBE4AA1  FFR5AA1  1",
    "operator" : null,
    "instant" : "preventive",
    "optimized" : true,
    "monitored" : false,
    "reliabilityMargin" : 0.0,
    "iMax" : [ 2000.0 ],
    "nominalV" : [ 400.0 ],
    "thresholds" : [ {
      "unit" : "ampere",
      "min" : -1000.0,
      "max" : 1000.0,
      "side" : "right"
    } ]
  }, {
    "id" : "DDE2AA1  NNL3AA1  1 - preventive",
    "name" : "de2_nl3_n",
    "networkElementId" : "DDE2AA1  NNL3AA1  1",
    "operator" : null,
    "instant" : "preventive",
    "optimized" : true,
    "monitored" : false,
    "reliabilityMargin" : 0.0,
    "iMax" : [ 2000.0 ],
    "nominalV" : [ 400.0 ],
    "thresholds" : [ {
      "unit" : "ampere",
      "min" : -5000.0,
      "max" : 5000.0,
      "side" : "right"
    } ]
  }, {
    "id" : "FFR2AA1  DDE3AA1  1 - preventive",
    "name" : "fr2_de3_n",
    "networkElementId" : "FFR2AA1  DDE3AA1  1",
    "operator" : null,
    "instant" : "preventive",
    "optimized" : true,
    "monitored" : false,
    "reliabilityMargin" : 0.0,
    "iMax" : [ 2000.0 ],
    "nominalV" : [ 400.0 ],
    "thresholds" : [ {
      "unit" : "ampere",
      "min" : -1500.0,
      "max" : 1500.0,
      "side" : "right"
    } ]
  }, {
    "id" : "FFR4AA1  DDE1AA1  1 - preventive",
    "name" : "fr4_de1_n",
    "networkElementId" : "FFR4AA1  DDE1AA1  1",
    "operator" : null,
    "instant" : "preventive",
    "optimized" : true,
    "monitored" : false,
    "reliabilityMargin" : 0.0,
    "iMax" : [ 2000.0 ],
    "nominalV" : [ 400.0 ],
    "thresholds" : [ {
      "unit" : "ampere",
      "min" : -1500.0,
      "max" : 1500.0,
      "side" : "right"
    } ]
  }, {
    "id" : "FFR4AA1  DDE4AA1  1 - preventive",
    "name" : "fr4_de4_n",
    "networkElementId" : "FFR4AA1  DDE4AA1  1",
    "operator" : null,
    "instant" : "preventive",
    "optimized" : true,
    "monitored" : false,
    "reliabilityMargin" : 0.0,
    "iMax" : [ 2000.0 ],
    "nominalV" : [ 400.0 ],
    "thresholds" : [ {
      "unit" : "ampere",
      "min" : -1000.0,
      "max" : 1000.0,
      "side" : "right"
    } ]
  }, {
    "id" : "NNL2AA1  BBE3AA1  1 - preventive",
    "name" : "nl2_be3_n",
    "networkElementId" : "NNL2AA1  BBE3AA1  1",
    "operator" : null,
    "instant" : "preventive",
    "optimized" : true,
    "monitored" : false,
    "reliabilityMargin" : 0.0,
    "iMax" : [ 2000.0 ],
    "nominalV" : [ 400.0 ],
    "thresholds" : [ {
      "unit" : "ampere",
      "min" : -5000.0,
      "max" : 5000.0,
      "side" : "right"
    } ]
  } ],
  "angleCnecs" : [ ],
  "voltageCnecs" : [ ],
  "pstRangeActions" : [ {
    "id" : "pst_be",
    "name" : "pst_be",
    "operator" : "be",
    "onInstantUsageRules" : [ {
      "instant" : "preventive",
      "usageMethod" : "available"
    } ],
    "networkElementId" : "BBE2AA1  BBE3AA1  1",
    "initialTap" : 0,
    "tapToAngleConversionMap" : {
      "-1" : -0.3896097993971608,
      "0" : 0.0,
      "-2" : -0.7792105912934298,
      "1" : 0.3896097993971608,
      "-3" : -1.1687933694373345,
      "2" : 0.7792105912934298,
      "-4" : -1.5583491300758083,
      "3" : 1.1687933694373345,
      "-5" : -1.9478688732023104,
      "4" : 1.5583491300758083,
      "-6" : -2.337343603803646,
      "5" : 1.9478688732023104,
      "-7" : -2.7267643331050597,
      "6" : 2.337343603803646,
      "-8" : -3.1161220798131644,
      "7" : 2.7267643331050597,
      "-9" : -3.505407871356285,
      "8" : 3.1161220798131644,
      "-10" : -3.894612745121778,
      "9" : 3.505407871356285,
      "-11" : -4.283727749689918,
      "10" : 3.894612745121778,
      "-12" : -4.672743946063913,
      "11" : 4.283727749689918,
      "-13" : -5.061652408895631,
      "12" : 4.672743946063913,
      "-14" : -5.4504442277066305,
      "13" : 5.061652408895631,
      "-15" : -5.839110508104064,
      "14" : 5.4504442277066305,
      "-16" : -6.2276423729910535,
      "15" : 5.839110508104064,
      "16" : 6.2276423729910535
    },
    "ranges" : [ {
      "min" : -16,
      "max" : 16,
      "rangeType" : "absolute"
    } ]
  }, {
    "id" : "pst_fr",
    "name" : "pst_fr",
    "operator" : "fr",
    "onInstantUsageRules" : [ {
      "instant" : "curative",
      "usageMethod" : "available"
    } ],
    "networkElementId" : "FFR2AA1  FFR4AA1  1",
    "initialTap" : 5,
    "tapToAngleConversionMap" : {
      "-1" : -0.3896097993971608,
      "0" : 0.0,
      "-2" : -0.7792105912934298,
      "1" : 0.3896097993971608,
      "-3" : -1.1687933694373345,
      "2" : 0.7792105912934298,
      "-4" : -1.5583491300758083,
      "3" : 1.1687933694373345,
      "-5" : -1.9478688732023104,
      "4" : 1.5583491300758083,
      "-6" : -2.337343603803646,
      "5" : 1.9478688732023104,
      "-7" : -2.7267643331050597,
      "6" : 2.337343603803646,
      "-8" : -3.1161220798131644,
      "7" : 2.7267643331050597,
      "-9" : -3.505407871356285,
      "8" : 3.1161220798131644,
      "-10" : -3.894612745121778,
      "9" : 3.505407871356285,
      "-11" : -4.283727749689918,
      "10" : 3.894612745121778,
      "-12" : -4.672743946063913,
      "11" : 4.283727749689918,
      "-13" : -5.061652408895631,
      "12" : 4.672743946063913,
      "-14" : -5.4504442277066305,
      "13" : 5.061652408895631,
      "-15" : -5.839110508104064,
      "14" : 5.4504442277066305,
      "-16" : -6.2276423729910535,
      "15" : 5.839110508104064,
      "16" : 6.2276423729910535
    },
    "ranges" : [ {
      "min" : -10,
      "max" : 10,
      "rangeType" : "relativeToPreviousInstant"
    } ]
  } ],
  "hvdcRangeActions" : [ ],
  "injectionRangeActions" : [ ],
  "counterTradeRangeActions" : [ ],
  "networkActions" : [ {
    "id" : "close_de3_de4",
    "name" : "close_de3_de4",
    "operator" : "de",
    "onInstantUsageRules" : [ {
      "instant" : "preventive",
      "usageMethod" : "available"
    } ],
    "topologicalActions" : [ {
      "networkElementId" : "DDE3AA1  DDE4AA1  1",
      "actionType" : "close"
    } ]
  }, {
    "id" : "close_fr1_fr5",
    "name" : "close_fr1_fr5",
    "operator" : "fr",
    "onInstantUsageRules" : [ {
      "instant" : "curative",
      "usageMethod" : "available"
    } ],
    "topologicalActions" : [ {
      "networkElementId" : "FFR1AA1  FFR5AA1  1",
      "actionType" : "close"
    } ]
  }, {
    "id" : "open_be1_be4",
    "name" : "open_be1_be4",
    "operator" : "be",
    "onInstantUsageRules" : [ {
      "instant" : "preventive",
      "usageMethod" : "available"
    } ],
    "topologicalActions" : [ {
      "networkElementId" : "BBE1AA1  BBE4AA1  1",
      "actionType" : "open"
    } ]
  }, {
    "id" : "open_fr1_fr2",
    "name" : "open_fr1_fr2",
    "operator" : "fr",
    "onInstantUsageRules" : [ {
      "instant" : "preventive",
      "usageMethod" : "available"
    } ],
    "topologicalActions" : [ {
      "networkElementId" : "FFR1AA1  FFR2AA1  1",
      "actionType" : "open"
    } ]
  }, {
    "id" : "open_fr1_fr3",
    "name" : "open_fr1_fr3",
    "operator" : "fr",
    "onInstantUsageRules" : [ {
      "instant" : "curative",
      "usageMethod" : "available"
    } ],
    "topologicalActions" : [ {
      "networkElementId" : "FFR1AA1  FFR3AA1  1",
      "actionType" : "open"
    } ]
  } ]
}
