=== powsybl/powsybl-open-rao/data/crac/crac-io/crac-io-json/src/main/resources/schemas/crac/crac-v1.0.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema#",
  "$id": "resource:/schemas/crac/crac-v1.0.json",
  "description": "Contingency list, Remedial Actions and additional Constraints",
  "title": "CRAC",
  "type": "object",
  "properties": {
    "type": {
      "const": "CRAC"
    },
    "version": {
      "const": "1.0"
    },
    "info": {
      "description": "Information about the CRAC",
      "type": "string"
    },
    "id": {
      "description": "The unique identifier of the CRAC",
      "type": "string"
    },
    "name": {
      "description": "The name of the CRAC",
      "type": "string"
    },
    "networkElementsNamePerId": {
      "description": "A map of network element names indexed by their identifiers",
      "type": "object",
      "additionalProperties": {
        "type": "string"
      }
    },
    "contingencies": {
      "description": "The list of contingencies to be studied",
      "type": "array",
      "items": {
        "$ref": "../contingency/contingency-v1.0.json"
      }
    },
    "flowCnecs": {
      "description": "The list of flow CNECs to be monitored",
      "type": "array",
      "items": {
        "items": {
          "$ref": "../flow-cnec/flow-cnec-v1.0.json"
        }
      }
    },
    "pstRangeActions": {
      "description": "The list of PST range actions",
      "type": "array",
      "items": {
        "$ref": "../pst-range-action/pst-range-action-v1.0.json"
      }
    },
    "hvdcRangeActions": {
      "description": "The list of HVDC range actions",
      "type": "array",
      "items": {
        "$ref": "../hvdc-range-action/hvdc-range-action-v1.0.json"
      }
    },
    "networkActions": {
      "description": "The list of network actions",
      "type": "array",
      "items": {
        "$ref": "../network-action/network-action-v1.0.json"
      }
    },
    "extensions": {
      "type": "object",
      "additionalProperties": true
    }
  },
  "additionalProperties": false,
  "required": [
    "type",
    "version",
    "id",
    "name"
  ]
}

=== powsybl/powsybl-open-rao/ra-optimisation/search-tree-rao/src/test/resources/crac/small-crac-purely-virtual-curative.json
{
  "type" : "CRAC",
  "version" : "1.0",
  "id": "LS_unsecure",
  "name": "LS_unsecure",
  "networkElementsNamePerId": { },
  "contingencies": [
    {
      "id": "N-1 NL1-NL3",
      "networkElementsIds": [
        "NNL1AA1  NNL2AA1  1"
      ]
    }
  ],
  "flowCnecs": [
    {
      "id": "Tieline BE FR - Defaut - N-1 NL1-NL3",
      "name": "Tieline BE FR",
      "networkElementId": "BBE2AA1  FFR3AA1  1",
      "operator" : "FR",
      "thresholds": [ {
        "unit": "megawatt",
        "max": 750,
        "min" : -750,
        "rule" : "onRightSide"
      } ],
      "contingencyId": "N-1 NL1-NL3",
      "instant" : "curative",
      "optimized": true,
      "nominalV" : [ 380.0 ]
    },
    {
      "id": "Tieline BE FR - N - preventive",
      "name": "Tieline BE FR",
      "networkElementId": "BBE2AA1  FFR3AA1  1",
      "operator" : "FR",
      "thresholds": [ {
        "unit": "megawatt",
        "max": 750,
        "min" : -750,
        "rule" : "onLeftSide"
      } ],
      "instant": "preventive",
      "optimized": true,
      "nominalV" : [ 380.0 ]
    }
  ],
  "pstRangeActions": [
    {
      "id": "PRA_PST_BE",
      "name": "PRA_PST_BE",
      "operator": "BE",
      "initialTap": 0,
      "speed": 1,
      "tapToAngleConversionMap" : {
        "-1" : -0.3896097993971608,
        "0" : 0.0,
        "-2" : -0.7792105912934298,
        "1" : 0.3896097993971608,
        "-3" : -1.1687933694373345,
        "2" : 0.7792105912934298,
        "-4" : -1.5583491300758083,
        "3" : 1.1687933694373345,
        "-5" : -1.9478688732023104,
        "4" : 1.5583491300758083,
        "-6" : -2.337343603803646,
        "5" : 1.9478688732023104,
        "-7" : -2.7267643331050597,
        "6" : 2.337343603803646,
        "-8" : -3.1161220798131644,
        "7" : 2.7267643331050597,
        "-9" : -3.505407871356285,
        "8" : 3.1161220798131644,
        "-10" : -3.894612745121778,
        "9" : 3.505407871356285,
        "-11" : -4.283727749689918,
        "10" : 3.894612745121778,
        "-12" : -4.672743946063913,
        "11" : 4.283727749689918,
        "-13" : -5.061652408895631,
        "12" : 4.672743946063913,
        "-14" : -5.4504442277066305,
        "13" : 5.061652408895631,
        "-15" : -5.839110508104064,
        "14" : 5.4504442277066305,
        "-16" : -6.2276423729910535,
        "15" : 5.839110508104064,
        "16" : 6.2276423729910535
      },
      "freeToUseUsageRules": [
        {
          "usageMethod": "available",
          "instant": "preventive"
        }
      ],
      "ranges": [
        {
          "min": -12,
          "max": 12,
          "rangeType": "absolute"
        }
      ],
      "networkElementId": "BBE2AA1  BBE3AA1  1"
    },
    {
      "id": "CRA_PST_BE",
      "name": "CRA_PST_BE",
      "operator": "BE",
      "initialTap": 0,
      "speed": 1,
      "tapToAngleConversionMap" : {
        "-1" : -0.3896097993971608,
        "0" : 0.0,
        "-2" : -0.7792105912934298,
        "1" : 0.3896097993971608,
        "-3" : -1.1687933694373345,
        "2" : 0.7792105912934298,
        "-4" : -1.5583491300758083,
        "3" : 1.1687933694373345,
        "-5" : -1.9478688732023104,
        "4" : 1.5583491300758083,
        "-6" : -2.337343603803646,
        "5" : 1.9478688732023104,
        "-7" : -2.7267643331050597,
        "6" : 2.337343603803646,
        "-8" : -3.1161220798131644,
        "7" : 2.7267643331050597,
        "-9" : -3.505407871356285,
        "8" : 3.1161220798131644,
        "-10" : -3.894612745121778,
        "9" : 3.505407871356285,
        "-11" : -4.283727749689918,
        "10" : 3.894612745121778,
        "-12" : -4.672743946063913,
        "11" : 4.283727749689918,
        "-13" : -5.061652408895631,
        "12" : 4.672743946063913,
        "-14" : -5.4504442277066305,
        "13" : 5.061652408895631,
        "-15" : -5.839110508104064,
        "14" : 5.4504442277066305,
        "-16" : -6.2276423729910535,
        "15" : 5.839110508104064,
        "16" : 6.2276423729910535
      },
      "onStateUsageRules" : [ {
        "instant" : "curative",
        "contingencyId" : "N-1 NL1-NL3",
        "usageMethod" : "available"
      } ],
      "ranges": [
        {
          "min": -15,
          "max": 15,
          "rangeType": "absolute"
        }
      ],
      "networkElementId": "BBE2AA1  BBE3AA1  1"
    }
  ],
  "networkActions": []
}

=== powsybl/powsybl-open-rao/data/crac/crac-util/src/test/resources/deprecated-crac-for-aliases-2.json
{
  "type" : "CRAC",
  "version" : "1.0",
  "id" : "LS_parade_pst_direct",
  "name" : "LS_parade_pst_direct",
  "networkElementsNamePerId": { },
  "contingencies" : [ {
    "id" : "Contingency 1",
    "networkElementsIds" : [ "FFR1AA1G FFR2AA1H 1" ]
  }, {
      "id" : "Contingency Interco",
      "networkElementsIds" : [ "FFR2AA1H DDE3AA1F 1" ]
    }],
  "flowCnecs" : [ {
    "id" : "FFR2AA1H DDE3AA1F 1 - Curatif - Contingency 1",
    "name" : "Tie-line FR DE",
    "networkElementId" : "FFR2AA1H DDE3AA1F 1",
    "contingencyId" : "Contingency 1",
    "instant": "curative",
    "frm" : 0.0,
    "nominalV" : [ 380.0 ],
    "thresholds" : [ {
      "unit" : "ampere",
      "rule" : "onLeftSide",
      "max" : 1500.0
    } ],
    "extensions" : {
      "CnecResultExtension" : {
        "resultsPerVariant" : {
          "preOptimisationResults-3788be4e-3998-4fe8-8d7d-e5088ab87edf" : {
            "type" : "cnec-result",
            "flowInMW" : 1451.9127197265625,
            "flowInA" : 2097.820556640625,
            "minThresholdInMW" : -Infinity,
            "maxThresholdInMW" : 1039.2304845413264,
            "minThresholdInA" : -Infinity,
            "maxThresholdInA" : 1500.0
          },
          "postOptimisationResults-5541441d-b49f-4670-bb70-d30e60c8ccaa" : {
            "type" : "cnec-result",
            "flowInMW" : 1286.8662109375,
            "flowInA" : 1858.9375,
            "minThresholdInMW" : -Infinity,
            "maxThresholdInMW" : 1039.2304845413264,
            "minThresholdInA" : -Infinity,
            "maxThresholdInA" : 1500.0
          }
        }
      }
    }
  }, {
    "id" : "DDE1AA1D DDE2AA1E 1 - Défaut - Contingency 1",
    "name" : "Line DE1 DE2",
    "networkElementId" : "DDE1AA1D DDE2AA1E 1",
    "contingencyId" : "Contingency 1",
    "instant": "outage",
    "frm" : -1.0,
    "nominalV" : [ 380.0 ],
    "thresholds" : [ {
      "unit" : "ampere",
      "rule" : "onLeftSide",
      "min" : -1500.0,
      "max" : 1500.0
    } ],
    "extensions" : {
      "CnecResultExtension" : {
        "resultsPerVariant" : {
          "preOptimisationResults-3788be4e-3998-4fe8-8d7d-e5088ab87edf" : {
            "type" : "cnec-result",
            "flowInMW" : -349.3979797363281,
            "flowInA" : -504.3426208496094,
            "minThresholdInMW" : -1039.2304845413264,
            "maxThresholdInMW" : 1039.2304845413264,
            "minThresholdInA" : -1500.0,
            "maxThresholdInA" : 1500.0
          },
          "postOptimisationResults-5541441d-b49f-4670-bb70-d30e60c8ccaa" : {
            "type" : "cnec-result",
            "flowInMW" : -404.3988952636719,
            "flowInA" : -583.7461547851562,
            "minThresholdInMW" : -1039.2304845413264,
            "maxThresholdInMW" : 1039.2304845413264,
            "minThresholdInA" : -1500.0,
            "maxThresholdInA" : 1500.0
          }
        }
      }
    }
  }, {
    "id" : "DDE1AA1D DDE2AA1E 1 - Curatif - Contingency 1",
    "name" : "Line DE1 DE2",
    "networkElementId" : "DDE1AA1D DDE2AA1E 1",
    "contingencyId" : "Contingency 1",
    "instant": "curative",
    "frm" : 2.0,
    "nominalV" : [ 380.0 ],
    "thresholds" : [ {
      "unit" : "ampere",
      "rule" : "onLeftSide",
      "min" : -1500.0,
      "max" : 1500.0
    } ],
    "extensions" : {
      "CnecResultExtension" : {
        "resultsPerVariant" : {
          "preOptimisationResults-3788be4e-3998-4fe8-8d7d-e5088ab87edf" : {
            "type" : "cnec-result",
            "flowInMW" : -349.3979797363281,
            "flowInA" : -504.3426208496094,
            "minThresholdInMW" : -1039.2304845413264,
            "maxThresholdInMW" : 1039.2304845413264,
            "minThresholdInA" : -1500.0,
            "maxThresholdInA" : 1500.0
          },
          "postOptimisationResults-5541441d-b49f-4670-bb70-d30e60c8ccaa" : {
            "type" : "cnec-result",
            "flowInMW" : -404.3988952636719,
            "flowInA" : -583.7461547851562,
            "minThresholdInMW" : -1039.2304845413264,
            "maxThresholdInMW" : 1039.2304845413264,
            "minThresholdInA" : -1500.0,
            "maxThresholdInA" : 1500.0
          }
        }
      }
    }
  }, {
    "id" : "DDE1AA1D DDE2AA1E 1 - N - preventive",
    "name" : "Line DE1 DE2",
    "networkElementId" : "DDE1AA1D DDE2AA1E 1",
    "instant" : "preventive",
    "frm" : 3.0,
    "nominalV" : [ 380.0 ],
    "thresholds" : [ {
      "unit" : "ampere",
      "rule" : "onLeftSide",
      "min" : -1500.0,
      "max" : 1500.0
    } ],
    "extensions" : {
      "CnecResultExtension" : {
        "resultsPerVariant" : {
          "preOptimisationResults-3788be4e-3998-4fe8-8d7d-e5088ab87edf" : {
            "type" : "cnec-result",
            "flowInMW" : -333.455078125,
            "flowInA" : -481.3270568847656,
            "minThresholdInMW" : -1039.2304845413264,
            "maxThresholdInMW" : 1039.2304845413264,
            "minThresholdInA" : -1500.0,
            "maxThresholdInA" : 1500.0
          },
          "postOptimisationResults-5541441d-b49f-4670-bb70-d30e60c8ccaa" : {
            "type" : "cnec-result",
            "flowInMW" : -391.2393493652344,
            "flowInA" : -564.74755859375,
            "minThresholdInMW" : -1039.2304845413264,
            "maxThresholdInMW" : 1039.2304845413264,
            "minThresholdInA" : -1500.0,
            "maxThresholdInA" : 1500.0
          }
        }
      }
    }
  }, {
    "id" : "FFR2AA1H DDE3AA1F 1 - Défaut - Contingency 1",
    "name" : "Tie-line FR DE",
    "networkElementId" : "FFR2AA1H DDE3AA1F 1",
    "contingencyId" : "Contingency 1",
    "instant": "outage",
    "frm" : 4.0,
    "nominalV" : [ 380.0 ],
    "thresholds" : [ {
      "unit" : "ampere",
      "rule" : "onLeftSide",
      "max" : 1500.0
    } ],
    "extensions" : {
      "CnecResultExtension" : {
        "resultsPerVariant" : {
          "preOptimisationResults-3788be4e-3998-4fe8-8d7d-e5088ab87edf" : {
            "type" : "cnec-result",
            "flowInMW" : 1451.9127197265625,
            "flowInA" : 2097.820556640625,
            "minThresholdInMW" : -Infinity,
            "maxThresholdInMW" : 1039.2304845413264,
            "minThresholdInA" : -Infinity,
            "maxThresholdInA" : 1500.0
          },
          "postOptimisationResults-5541441d-b49f-4670-bb70-d30e60c8ccaa" : {
            "type" : "cnec-result",
            "flowInMW" : 1286.8662109375,
            "flowInA" : 1858.9375,
            "minThresholdInMW" : -Infinity,
            "maxThresholdInMW" : 1039.2304845413264,
            "minThresholdInA" : -Infinity,
            "maxThresholdInA" : 1500.0
          }
        }
      }
    }
  }, {
    "id" : "FFR2AA1H DDE3AA1F 1 - N - preventive",
    "name" : "Tie-line FR DE",
    "networkElementId" : "FFR2AA1H DDE3AA1F 1",
    "instant" : "preventive",
    "frm" : 5.0,
    "nominalV" : [ 380.0 ],
    "thresholds" : [ {
      "unit" : "ampere",
      "rule" : "onLeftSide",
      "max" : 1500.0
    } ],
    "extensions" : {
      "CnecResultExtension" : {
        "resultsPerVariant" : {
          "preOptimisationResults-3788be4e-3998-4fe8-8d7d-e5088ab87edf" : {
            "type" : "cnec-result",
            "flowInMW" : 1499.7794189453125,
            "flowInA" : 2167.1318359375,
            "minThresholdInMW" : -Infinity,
            "maxThresholdInMW" : 1039.2304845413264,
            "minThresholdInA" : -Infinity,
            "maxThresholdInA" : 1500.0
          },
          "postOptimisationResults-5541441d-b49f-4670-bb70-d30e60c8ccaa" : {
            "type" : "cnec-result",
            "flowInMW" : 1326.383056640625,
            "flowInA" : 1916.11865234375,
            "minThresholdInMW" : -Infinity,
            "maxThresholdInMW" : 1039.2304845413264,
            "minThresholdInA" : -Infinity,
            "maxThresholdInA" : 1500.0
          }
        }
      }
    }
  } ],
  "pstRangeActions" : [ {
    "id" : "PST1",
    "name" : "PST1",
    "operator" : "FR",
    "initialTap": 0,
    "tapToAngleConversionMap" : {
      "-3" : 0.0,
      "-2" : 0.5,
      "-1" : 1.0,
      "0" : 1.5,
      "1" : 2.0,
      "2" : 2.5,
      "3" : 3.0
    },
    "freeToUseUsageRules" : [ {
      "usageMethod" : "available",
      "instant" : "preventive"
    } ],
    "networkElementId" : "BBE2AA1  BBE3AA1  1",
    "ranges" : [ {
      "min" : 1.0,
      "max" : 33.0,
      "rangeType" : "absolute"
    } ]
  } ],
  "networkActions" : [ {
    "id" : "complexNetworkActionId",
    "name" : "complexNetworkActionName",
    "operator" : "RTE",
    "freeToUseUsageRules" : [ {
      "instant" : "preventive",
      "usageMethod" : "available"
    } ],
    "topologicalActions" : [ {
      "networkElementId" : "FFR2AA1H DDE3AA1F 1",
      "actionType" : "close"
    } ],
    "pstSetpoints" : [ {
      "networkElementId" : "BBE2AA1  BBE3AA1  1",
      "setpoint" : 5
    } ],
    "extensions" : {

    }
  }],
  "extensions" : {
    "ResultVariantManager" : {
      "variantIds" : [ "preOptimisationResults-3788be4e-3998-4fe8-8d7d-e5088ab87edf", "postOptimisationResults-5541441d-b49f-4670-bb70-d30e60c8ccaa" ]
    },
    "CracResultExtension" : {
      "resultsPerVariant" : {
        "preOptimisationResults-3788be4e-3998-4fe8-8d7d-e5088ab87edf" : {
          "type" : "crac-result",
          "networkSecurityStatus" : "UNSECURED",
          "functionalCost" : 460.5489344039861,
          "virtualCost" : 0.0
        },
        "postOptimisationResults-5541441d-b49f-4670-bb70-d30e60c8ccaa" : {
          "type" : "crac-result",
          "networkSecurityStatus" : "UNSECURED",
          "functionalCost" : 287.1525720992986,
          "virtualCost" : 0.0
        }
      }
    }
  },
  "hvdcRangeActions": [ ]
}
