=== powsybl/powsybl-open-rao/data/crac/crac-io/crac-io-json/src/main/resources/schemas/crac/crac-v2.1.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema#",
  "$id": "resource:/schemas/crac/crac-v2.1.json",
  "description": "Contingency list, Remedial Actions and additional Constraints",
  "title": "CRAC",
  "type": "object",
  "properties": {
    "type": {
      "const": "CRAC"
    },
    "version": {
      "const": "2.1"
    },
    "info": {
      "description": "Information about the CRAC",
      "type": "string"
    },
    "id": {
      "description": "The unique identifier of the CRAC",
      "type": "string"
    },
    "name": {
      "description": "The name of the CRAC",
      "type": "string"
    },
    "instants": {
      "description": "The list of instants at which a CNEC can be monitored and a Remedial Action applied",
      "type": "array",
      "items": {
        "$ref": "../instant/instant-v2.0.json"
      }
    },
    "ra-usage-limits-per-instant": {
      "description": "The list of remedial action usage limitations for each instant",
      "type": "array",
      "items": {
        "$ref": "../ra-usage-limits-per-instant/ra-usage-limits-per-instant-v2.1.json"
      }
    },
    "networkElementsNamePerId": {
      "description": "A map of network element names indexed by their identifiers",
      "type": "object",
      "additionalProperties": {
        "type": "string"
      }
    },
    "contingencies": {
      "description": "The list of contingencies to be studied",
      "type": "array",
      "items": {
        "$ref": "../contingency/contingency-v1.0.json"
      }
    },
    "flowCnecs": {
      "description": "The list of flow CNECs to be monitored",
      "type": "array",
      "items": {
        "items": {
          "$ref": "../flow-cnec/flow-cnec-v1.7.json"
        }
      }
    },
    "angleCnecs": {
      "description": "The list of angle CNECs to be monitored",
      "type": "array",
      "items": {
        "items": {
          "$ref": "../angle-cnec/angle-cnec-v1.4.json"
        }
      }
    },
    "voltageCnecs": {
      "description": "The list of voltage CNECs to be monitored",
      "type": "array",
      "items": {
        "items": {
          "$ref": "../voltage-cnec/voltage-cnec-v1.5.json"
        }
      }
    },
    "pstRangeActions": {
      "description": "The list of PST range actions",
      "type": "array",
      "items": {
        "$ref": "../pst-range-action/pst-range-action-v2.0.json"
      }
    },
    "hvdcRangeActions": {
      "description": "The list of HVDC range actions",
      "type": "array",
      "items": {
        "$ref": "../hvdc-range-action/hvdc-range-action-v2.0.json"
      }
    },
    "injectionRangeActions": {
      "description": "The list of injection range actions",
      "type": "array",
      "items": {
        "$ref": "../injection-range-action/injection-range-action-v2.0.json"
      }
    },
    "counterTradeRangeActions": {
      "description": "The list of counter-trade range actions",
      "type": "array",
      "items": {
        "$ref": "../counter-trade-range-action/counter-trade-range-action-v2.0.json"
      }
    },
    "networkActions": {
      "description": "The list of network actions",
      "type": "array",
      "items": {
        "$ref": "../network-action/network-action-v2.0.json"
      }
    }
  },
  "additionalProperties": false,
  "required": [
    "type",
    "version",
    "id",
    "name"
  ]
}

=== powsybl/powsybl-open-rao/tests/src/test/resources/files/crac/epic19/SL_ep19us6case8.json
{
  "type" : "CRAC",
  "version" : "2.1",
  "info" : "Generated by Open RAO http://farao-community.github.io",
  "id" : "curative_7",
  "name" : "curative_7",
  "instants" : [ {
    "id" : "preventive",
    "kind" : "PREVENTIVE"
  }, {
    "id" : "outage",
    "kind" : "OUTAGE"
  }, {
    "id" : "auto",
    "kind" : "AUTO"
  }, {
    "id" : "curative",
    "kind" : "CURATIVE"
  } ],
  "ra-usage-limits-per-instant" : [ {
    "instant": "curative",
    "max-ra" : 0,
    "max-topo-per-tso" : { },
    "max-pst-per-tso" : { },
    "max-ra-per-tso" : { }
  } ],
  "networkElementsNamePerId" : { },
  "contingencies" : [ {
    "id" : "co1_fr2_fr3_1",
    "networkElementsIds" : [ "FFR2AA1  FFR3AA1  1" ]
  } ],
  "flowCnecs" : [ {
    "id" : "BBE1AA1  FFR5AA1  1 - preventive",
    "name" : "be1_fr5_n",
    "networkElementId" : "BBE1AA1  FFR5AA1  1",
    "operator" : null,
    "instant" : "preventive",
    "optimized" : true,
    "monitored" : false,
    "reliabilityMargin" : 0.0,
    "iMax" : [ 2000.0 ],
    "nominalV" : [ 400.0 ],
    "thresholds" : [ {
      "unit" : "ampere",
      "min" : -1500.0,
      "max" : 1500.0,
      "side" : "right"
    } ]
  }, {
    "id" : "FFR3AA1  FFR5AA1  1 - co1_fr2_fr3_1 - curative",
    "name" : "fr3_fr5_co1",
    "networkElementId" : "FFR3AA1  FFR5AA1  1",
    "operator" : null,
    "instant" : "curative",
    "contingencyId" : "co1_fr2_fr3_1",
    "optimized" : true,
    "monitored" : false,
    "reliabilityMargin" : 0.0,
    "iMax" : [ 2000.0 ],
    "nominalV" : [ 400.0 ],
    "thresholds" : [ {
      "unit" : "ampere",
      "min" : -1000.0,
      "max" : 1000.0,
      "side" : "right"
    } ]
  } ],
  "angleCnecs" : [ ],
  "voltageCnecs" : [ ],
  "pstRangeActions" : [ {
    "id" : "pst_be",
    "name" : "pst_be",
    "operator" : "be",
    "onInstantUsageRules" : [ {
      "instant" : "curative",
      "usageMethod" : "available"
    } ],
    "networkElementId" : "BBE2AA1  BBE3AA1  1",
    "initialTap" : 0,
    "tapToAngleConversionMap" : {
      "-1" : -0.3896097993971608,
      "0" : 0.0,
      "-2" : -0.7792105912934298,
      "1" : 0.3896097993971608,
      "-3" : -1.1687933694373345,
      "2" : 0.7792105912934298,
      "-4" : -1.5583491300758083,
      "3" : 1.1687933694373345,
      "-5" : -1.9478688732023104,
      "4" : 1.5583491300758083,
      "-6" : -2.337343603803646,
      "5" : 1.9478688732023104,
      "-7" : -2.7267643331050597,
      "6" : 2.337343603803646,
      "-8" : -3.1161220798131644,
      "7" : 2.7267643331050597,
      "-9" : -3.505407871356285,
      "8" : 3.1161220798131644,
      "-10" : -3.894612745121778,
      "9" : 3.505407871356285,
      "-11" : -4.283727749689918,
      "10" : 3.894612745121778,
      "-12" : -4.672743946063913,
      "11" : 4.283727749689918,
      "-13" : -5.061652408895631,
      "12" : 4.672743946063913,
      "-14" : -5.4504442277066305,
      "13" : 5.061652408895631,
      "-15" : -5.839110508104064,
      "14" : 5.4504442277066305,
      "-16" : -6.2276423729910535,
      "15" : 5.839110508104064,
      "16" : 6.2276423729910535
    },
    "ranges" : [ {
      "min" : -16,
      "max" : 16,
      "rangeType" : "absolute"
    } ]
  }, {
    "id" : "pst_fr",
    "name" : "pst_fr",
    "operator" : "fr",
    "onInstantUsageRules" : [ {
      "instant" : "curative",
      "usageMethod" : "available"
    } ],
    "networkElementId" : "FFR2AA1  FFR4AA1  1",
    "initialTap" : 5,
    "tapToAngleConversionMap" : {
      "-1" : -0.3896097993971608,
      "0" : 0.0,
      "-2" : -0.7792105912934298,
      "1" : 0.3896097993971608,
      "-3" : -1.1687933694373345,
      "2" : 0.7792105912934298,
      "-4" : -1.5583491300758083,
      "3" : 1.1687933694373345,
      "-5" : -1.9478688732023104,
      "4" : 1.5583491300758083,
      "-6" : -2.337343603803646,
      "5" : 1.9478688732023104,
      "-7" : -2.7267643331050597,
      "6" : 2.337343603803646,
      "-8" : -3.1161220798131644,
      "7" : 2.7267643331050597,
      "-9" : -3.505407871356285,
      "8" : 3.1161220798131644,
      "-10" : -3.894612745121778,
      "9" : 3.505407871356285,
      "-11" : -4.283727749689918,
      "10" : 3.894612745121778,
      "-12" : -4.672743946063913,
      "11" : 4.283727749689918,
      "-13" : -5.061652408895631,
      "12" : 4.672743946063913,
      "-14" : -5.4504442277066305,
      "13" : 5.061652408895631,
      "-15" : -5.839110508104064,
      "14" : 5.4504442277066305,
      "-16" : -6.2276423729910535,
      "15" : 5.839110508104064,
      "16" : 6.2276423729910535
    },
    "ranges" : [ {
      "min" : -10,
      "max" : 10,
      "rangeType" : "relativeToPreviousInstant"
    } ]
  } ],
  "hvdcRangeActions" : [ ],
  "injectionRangeActions" : [ ],
  "counterTradeRangeActions" : [ ],
  "networkActions" : [ {
    "id" : "close_de3_de4",
    "name" : "close_de3_de4",
    "operator" : "de",
    "onInstantUsageRules" : [ {
      "instant" : "curative",
      "usageMethod" : "available"
    } ],
    "topologicalActions" : [ {
      "networkElementId" : "DDE3AA1  DDE4AA1  1",
      "actionType" : "close"
    } ]
  }, {
    "id" : "close_fr1_fr5",
    "name" : "close_fr1_fr5",
    "operator" : "fr",
    "onInstantUsageRules" : [ {
      "instant" : "curative",
      "usageMethod" : "available"
    } ],
    "topologicalActions" : [ {
      "networkElementId" : "FFR1AA1  FFR5AA1  1",
      "actionType" : "close"
    } ]
  }, {
    "id" : "open_be1_be4",
    "name" : "open_be1_be4",
    "operator" : "be",
    "onInstantUsageRules" : [ {
      "instant" : "curative",
      "usageMethod" : "available"
    } ],
    "topologicalActions" : [ {
      "networkElementId" : "BBE1AA1  BBE4AA1  1",
      "actionType" : "open"
    } ]
  }, {
    "id" : "open_fr1_fr2",
    "name" : "open_fr1_fr2",
    "operator" : "fr",
    "onInstantUsageRules" : [ {
      "instant" : "curative",
      "usageMethod" : "available"
    } ],
    "topologicalActions" : [ {
      "networkElementId" : "FFR1AA1  FFR2AA1  1",
      "actionType" : "open"
    } ]
  }, {
    "id" : "open_fr1_fr3",
    "name" : "open_fr1_fr3",
    "operator" : "fr",
    "onInstantUsageRules" : [ {
      "instant" : "curative",
      "usageMethod" : "available"
    } ],
    "topologicalActions" : [ {
      "networkElementId" : "FFR1AA1  FFR3AA1  1",
      "actionType" : "open"
    } ]
  } ]
}

=== powsybl/powsybl-open-rao/ra-optimisation/search-tree-rao/src/test/resources/crac/small-crac-ra-limits-per-instant-3-tsos.json
{
  "type" : "CRAC",
  "version" : "2.1",
  "info" : "Generated by Open RAO http://farao-community.github.io",
  "id" : "crac",
  "name" : "crac",
  "instants" : [ {
    "id" : "preventive",
    "kind" : "PREVENTIVE"
  }, {
    "id" : "outage",
    "kind" : "OUTAGE"
  }, {
    "id" : "curative1",
    "kind" : "CURATIVE"
  }, {
    "id" : "curative2",
    "kind" : "CURATIVE"
  }, {
    "id" : "curative3",
    "kind" : "CURATIVE"
  } ],
  "ra-usage-limits-per-instant" : [ {
    "instant" : "curative3",
    "max-ra" : 2147483647,
    "max-tso" : 3,
    "max-topo-per-tso" : { },
    "max-pst-per-tso" : { },
    "max-ra-per-tso" : { }
  }, {
    "instant" : "curative2",
    "max-ra" : 2147483647,
    "max-tso" : 2,
    "max-topo-per-tso" : { },
    "max-pst-per-tso" : { },
    "max-ra-per-tso" : { }
  }, {
    "instant" : "curative1",
    "max-ra" : 2147483647,
    "max-tso" : 2,
    "max-topo-per-tso" : { },
    "max-pst-per-tso" : { },
    "max-ra-per-tso" : { }
  } ],
  "networkElementsNamePerId" : { },
  "contingencies" : [ {
    "id" : "contingency",
    "name" : "CO",
    "networkElementsIds" : [ "NNL2AA1  BBE3AA1  1" ]
  } ],
  "flowCnecs" : [ {
    "id" : "FR2-DE3 - contingency - curative1",
    "name" : "FR2-DE3 - contingency - curative1",
    "networkElementId" : "FFR2AA1  DDE3AA1  1",
    "operator" : null,
    "instant" : "curative1",
    "contingencyId" : "contingency",
    "optimized" : true,
    "monitored" : false,
    "reliabilityMargin" : 0.0,
    "iMax" : [ NaN ],
    "nominalV" : [ 400.0 ],
    "thresholds" : [ {
      "unit" : "ampere",
      "min" : -800.0,
      "max" : 800.0,
      "side" : "left"
    } ]
  }, {
    "id" : "FR2-DE3 - contingency - curative2",
    "name" : "FR2-DE3 - contingency - curative2",
    "networkElementId" : "FFR2AA1  DDE3AA1  1",
    "operator" : null,
    "instant" : "curative2",
    "contingencyId" : "contingency",
    "optimized" : true,
    "monitored" : false,
    "reliabilityMargin" : 0.0,
    "iMax" : [ NaN ],
    "nominalV" : [ 400.0 ],
    "thresholds" : [ {
      "unit" : "ampere",
      "min" : -400.0,
      "max" : 400.0,
      "side" : "left"
    } ]
  }, {
    "id" : "FR2-DE3 - contingency - curative3",
    "name" : "FR2-DE3 - contingency - curative3",
    "networkElementId" : "FFR2AA1  DDE3AA1  1",
    "operator" : null,
    "instant" : "curative3",
    "contingencyId" : "contingency",
    "optimized" : true,
    "monitored" : false,
    "reliabilityMargin" : 0.0,
    "iMax" : [ NaN ],
    "nominalV" : [ 400.0 ],
    "thresholds" : [ {
      "unit" : "ampere",
      "min" : -400.0,
      "max" : 400.0,
      "side" : "left"
    } ]
  }, {
    "id" : "FR2-DE3 - contingency - outage",
    "name" : "FR2-DE3 - contingency - outage",
    "networkElementId" : "FFR2AA1  DDE3AA1  1",
    "operator" : null,
    "instant" : "outage",
    "contingencyId" : "contingency",
    "optimized" : true,
    "monitored" : false,
    "reliabilityMargin" : 0.0,
    "iMax" : [ NaN ],
    "nominalV" : [ 400.0 ],
    "thresholds" : [ {
      "unit" : "ampere",
      "min" : -1700.0,
      "max" : 1700.0,
      "side" : "left"
    } ]
  }, {
    "id" : "FR2-DE3 - preventive",
    "name" : "FR2-DE3 - preventive",
    "networkElementId" : "FFR2AA1  DDE3AA1  1",
    "operator" : null,
    "instant" : "preventive",
    "optimized" : true,
    "monitored" : false,
    "reliabilityMargin" : 0.0,
    "iMax" : [ NaN ],
    "nominalV" : [ 400.0 ],
    "thresholds" : [ {
      "unit" : "ampere",
      "min" : -1000.0,
      "max" : 1000.0,
      "side" : "left"
    } ]
  } ],
  "angleCnecs" : [ ],
  "voltageCnecs" : [ ],
  "pstRangeActions" : [ ],
  "hvdcRangeActions" : [ ],
  "injectionRangeActions" : [ ],
  "counterTradeRangeActions" : [ ],
  "networkActions" : [ {
    "id" : "close-fr2-de3-2",
    "name" : "close-fr2-de3-2",
    "operator" : "BE",
    "onContingencyStateUsageRules" : [ {
      "instant" : "curative1",
      "contingencyId" : "contingency",
      "usageMethod" : "available"
    }, {
      "instant" : "curative2",
      "contingencyId" : "contingency",
      "usageMethod" : "available"
    }, {
      "instant" : "curative3",
      "contingencyId" : "contingency",
      "usageMethod" : "available"
    } ],
    "topologicalActions" : [ {
      "networkElementId" : "FFR2AA1  DDE3AA1  2",
      "actionType" : "close"
    } ]
  }, {
    "id" : "close-fr2-de3-3",
    "name" : "close-fr2-de3-3",
    "operator" : "DE",
    "onContingencyStateUsageRules" : [ {
      "instant" : "curative1",
      "contingencyId" : "contingency",
      "usageMethod" : "available"
    }, {
      "instant" : "curative2",
      "contingencyId" : "contingency",
      "usageMethod" : "available"
    }, {
      "instant" : "curative3",
      "contingencyId" : "contingency",
      "usageMethod" : "available"
    } ],
    "topologicalActions" : [ {
      "networkElementId" : "FFR2AA1  DDE3AA1  3",
      "actionType" : "close"
    } ]
  }, {
    "id" : "close-fr2-de3-4",
    "name" : "close-fr2-de3-4",
    "operator" : "FR",
    "onContingencyStateUsageRules" : [ {
      "instant" : "curative1",
      "contingencyId" : "contingency",
      "usageMethod" : "available"
    }, {
      "instant" : "curative2",
      "contingencyId" : "contingency",
      "usageMethod" : "available"
    }, {
      "instant" : "curative3",
      "contingencyId" : "contingency",
      "usageMethod" : "available"
    } ],
    "topologicalActions" : [ {
      "networkElementId" : "FFR2AA1  DDE3AA1  4",
      "actionType" : "close"
    } ]
  } ]
}

=== powsybl/powsybl-open-rao/ra-optimisation/search-tree-rao/src/test/resources/crac/jsonCrac_ep15us12-5case8.json
{
  "type" : "CRAC",
  "version" : "2.1",
  "info" : "Generated by Open RAO http://farao-community.github.io",
  "id" : "20161215_0430_2D4_CRAC_FR",
  "name" : "20161215_0430_2D4_CRAC_FR",
  "instants" : [ {
    "id" : "preventive",
    "kind" : "PREVENTIVE"
  }, {
    "id" : "outage",
    "kind" : "OUTAGE"
  }, {
    "id" : "auto",
    "kind" : "AUTO"
  }, {
    "id" : "curative",
    "kind" : "CURATIVE"
  } ],
  "ra-usage-limits-per-instant" : [ {
    "instant": "curative",
    "max-ra" : 2,
    "max-tso" : 2147483647,
    "max-topo-per-tso" : { },
    "max-pst-per-tso" : { },
    "max-ra-per-tso" : { }
  } ],
  "networkElementsNamePerId" : { },
  "contingencies" : [ {
    "id" : "co1_be1_fr5",
    "networkElementsIds" : [ "BBE1AA11 FFR5AA11 1" ]
  } ],
  "flowCnecs" : [ {
    "id" : "be4_fr5_co1 - BBE4AA11->FFR5AA11  - co1_be1_fr5 - curative",
    "name" : "be4_fr5_co1",
    "networkElementId" : "BBE4AA11 FFR5AA11 1",
    "operator" : null,
    "instant" : "curative",
    "contingencyId" : "co1_be1_fr5",
    "optimized" : true,
    "monitored" : false,
    "reliabilityMargin" : 0.0,
    "iMax" : [ 2000.0 ],
    "nominalV" : [ 400.0 ],
    "thresholds" : [ {
      "unit" : "ampere",
      "min" : -433.0,
      "max" : 433.0,
      "side" : "left"
    } ]
  }, {
    "id" : "be4_fr5_co1 - BBE4AA11->FFR5AA11  - co1_be1_fr5 - outage",
    "name" : "be4_fr5_co1",
    "networkElementId" : "BBE4AA11 FFR5AA11 1",
    "operator" : null,
    "instant" : "outage",
    "contingencyId" : "co1_be1_fr5",
    "optimized" : true,
    "monitored" : false,
    "reliabilityMargin" : 0.0,
    "iMax" : [ 2000.0 ],
    "nominalV" : [ 400.0 ],
    "thresholds" : [ {
      "unit" : "ampere",
      "min" : -9999.0,
      "max" : 9999.0,
      "side" : "left"
    } ]
  }, {
    "id" : "be4_fr_5_n - BBE4AA11->FFR5AA11 - preventive",
    "name" : "be4_fr_5_n",
    "networkElementId" : "BBE4AA11 FFR5AA11 1",
    "operator" : null,
    "instant" : "preventive",
    "optimized" : true,
    "monitored" : false,
    "reliabilityMargin" : 0.0,
    "iMax" : [ 2000.0 ],
    "nominalV" : [ 400.0 ],
    "thresholds" : [ {
      "unit" : "ampere",
      "max" : 9999.0,
      "side" : "left"
    } ]
  } ],
  "angleCnecs" : [ ],
  "voltageCnecs" : [ ],
  "pstRangeActions" : [ {
    "id" : "PST_CRA_PST_be_BBE2AA11 BBE3AA11 1",
    "name" : "CRA_PST_be",
    "operator" : "FR",
    "onInstantUsageRules" : [ {
      "instant" : "curative",
      "usageMethod" : "available"
    } ],
    "networkElementId" : "BBE2AA11 BBE3AA11 1",
    "initialTap" : 0,
    "tapToAngleConversionMap" : {
      "-1" : -0.38960981369018555,
      "0" : 0.0,
      "-2" : -0.77921062707901,
      "1" : 0.38960981369018555,
      "-3" : -1.1687933206558228,
      "2" : 0.77921062707901,
      "-4" : -1.5583491325378418,
      "3" : 1.1687933206558228,
      "-5" : -1.9478689432144165,
      "4" : 1.5583491325378418,
      "-6" : -2.337343454360962,
      "5" : 1.9478689432144165,
      "-7" : -2.726764440536499,
      "6" : 2.337343454360962,
      "-8" : -3.116122007369995,
      "7" : 2.726764440536499,
      "-9" : -3.5054078102111816,
      "8" : 3.116122007369995,
      "-10" : -3.894613027572632,
      "9" : 3.5054078102111816,
      "-11" : -4.283727645874023,
      "10" : 3.894613027572632,
      "-12" : -4.672743797302246,
      "11" : 4.283727645874023,
      "-13" : -5.061652183532715,
      "12" : 4.672743797302246,
      "-14" : -5.450444221496582,
      "13" : 5.061652183532715,
      "-15" : -5.839110374450684,
      "14" : 5.450444221496582,
      "-16" : -6.22764253616333,
      "15" : 5.839110374450684,
      "16" : 6.22764253616333
    },
    "ranges" : [ {
      "min" : -16,
      "max" : 16,
      "rangeType" : "absolute"
    } ]
  } ],
  "hvdcRangeActions" : [ {
    "id" : "CRA_HVDC",
    "name" : "CRA_HVDC",
    "operator" : "FR",
    "onInstantUsageRules" : [ {
      "instant" : "curative",
      "usageMethod" : "available"
    } ],
    "initialSetpoint" : 0.0,
    "ranges" : [ {
      "min" : -2000.0,
      "max" : 2000.0
    } ],
    "networkElementId" : "BBE2AA11 FFR3AA11 1"
  } ],
  "injectionRangeActions" : [ ],
  "counterTradeRangeActions" : [ ],
  "networkActions" : [ ]
}
